//config.hpp
/*this file autamated generated by cmake*/

#pragma once

namespace levi {
const std::string way_to_shaders{"${CMAKE_CURRENT_SOURCE_DIR}/src/shaders/"};
}

namespace bombino {
const std::string way_to_objects{"${CMAKE_CURRENT_SOURCE_DIR}/src/resources/"};
}
