// texture.hpp

#pragma once

#include <cstddef>
#include <cstdint>

namespace levi {
class texture {
public:
  texture();
  texture(uint32_t gl_tex, size_t width, size_t height);

public:
  /**\brief this value is specifier generated by glGenTextures function*/
  uint32_t gl_tex;
  size_t width;
  size_t height;
};
}; // namespace levi
